<?php
session_start();

$questions = array(
"Carl and the Passions changed band name to what",
"How many rings on the Olympic flag",
"What colour is vermilion a shade of",
"King Zog ruled which country",
"What colour is Spock's blood",
"Where in your body is your patella",
"Where can you find London bridge today",
"What spirit is mixed with ginger beer in a Moscow mule",
"Who was the first man in space",
"What would you do with a Yashmak",
"Who betrayed Jesus to the Romans",
"Which animal lays eggs",
"On television what was Flipper",
"Who's band was The Quarrymen",
"Which was the most successful Grand National horse",
"Who starred as the Six Million Dollar Man",
"In the song Waltzing Matilda - What is a Jumbuck",
"Who was Dan Dare's greatest enemy in the Eagle",
"What is Dick Grayson better known as",
"What was given on the fourth day of Christmas",
"What was Skippy ( on TV )",
"What does a funambulist do",
"What is the name of Dennis the Menace's dog",
"What are bactrians and dromedaries",
"Who played The Fugitive",
"Who was the King of Swing",
"Who was the first man to fly across the channel",
"Who starred as Rocky Balboa",
"In which war was the charge of the Light Brigade",
"Who invented the television",
"Who would use a mashie niblick",
"In the song who killed Cock Robin",
"What do deciduous trees do",
"In golf what name is given to the No 3 wood",
"If you has caries who would you consult",
"What other name is Mellor’s famously known by",
"What did Jack Horner pull from his pie",
"How many feet in a fathom",
"which film had song Springtime for Hitler",
"Name the legless fighter pilot of ww2",
"What was the name of inn in Treasure Island",
"What was Erich Weiss better known as",
"Who sailed in the Nina - Pinta and Santa Maria",
"Which leader died in St Helena",
"Who wrote Gone with the Wind",
"What does ring a ring a roses refer to",
"Whose nose grew when he told a lie",
"Who has won the most Oscars",
"What would a Scotsman do with a spurtle",
"Which award has the words for valour on it",
"If you had pogonophobia what would you be afraid of",
"Who would take silk as part of their job",
"Who won an Oscar for the African Queen",
"Who sang the theme song in 9 to 5",
"What in business terms is the IMF",
"Ringo Star narrates which children's TV series",
"Which country grows the most fruit",
"Which company is owned by Bill Gates",
"What would you do with a maris piper",
"In Casablanca what is the name of the nightclub",
"What was the first James Bond book",
"What kind of animal is a lurcher",
"What is the currency of Austria",
"What is the Islamic equal to the red cross",
"In fable who sold a cow for five beans",
"How did Alfred Nobel make his money",
"Who was the first man to run a sub four minute mile",
"What are Munroes",
"Which car company makes the Celica",
"Air Lingus is the national airline of which country",
"Who discovered radium",
"What does an alopecia sufferer lack",
"Who painted The Haywain",
"Triskadeccaphobia is the fear of what",
"What is a baby rabbit called",
"Which country had The Dauphin as a ruler",
"Who did Michael Caine play in the Ipcress File (both names)",
"Who won Euro song contest Save All Your Kisses For Me",
"Which country had the guns of Naverone installed",
"Ictheologists study what",
"What is a Winston Churchill",
"Who or what lives in a formicarium",
"What type of acid is used in car batteries",
"It’s a flock of sheep what's a group of owls called",
"What animal would you find in a form",
"Who in books and films was the man of bronze",
"Who was Stan Laurels partner",
"What kind of food is Cullan Skink",
"What is classified by the A B O system",
"What plant does the Colorado beetle attack",
"Where did the Pied Piper play",
"To where in France do the sick make pilgrimages",
"In which city was the famous black hole",
"Christopher Cockerel invented what",
"Ray Bolger played who in The Wizard of Oz",
"Sabotage is French - What did the saboteurs use",
"Which part of the human body contains the most gold",
"If you had rubella what would you have caught",
"Mohs scale hardest substance is diamond - what's the softest",
"La Giaconda is better known as what",
"Who wrote the Opera Madam Butterfly",
"What links - Goa - Kerula - Assam - Bihar",
"Eric Arthur Blaire was the real name of which author",
"Names - Baker Cook obvious what did Cordwainer do",
"Which country do Sinologists study",
"Rudy Stevens became famous under which name",
"Which non alcoholic cordial is made from pomegranates",
"What is Orchesis - either professional or amateur",
"Taken literally what should you see in a Hippodrome",
"Who wrote the Man in the Iron Mask",
"Which 1993 Disney film starred Bet Middler as a witch",
"Who piloted the first flight across the English channel",
"What was the first James Bond film",
"What 1991 film won best film, actor, actress, director Oscars",
"What was the capital of Ethiopia",
"Aescapalious emblem staff snake Greek Roman god of what",
"Giacomo Agostini - 122 Grand Prix 15 world titles what sport",
"What is the largest state in the USA",
"Led Deighton trilogy Game Set Match What 3 Capitals",
"Alan Stuart Konigsberg famous as who",
"Which human rights organisation founded 1961 got Nobel 1977",
"Whose autobiography was The long walk to Freedom",
"What was discovered in 1922 by Howard Carter",
"Clyde Tonbaugh discovered what planet in 1930",
"Who won the women's heptathlon at Seoul in 1988",
"Who wrote Northanger Abbey",
"Who ran through the streets naked crying Eureka",
"Who composed the Brandeberg concertos full names",
"Who won the World Series in 1987",
"What is the correct term of address to the Pope",
"In which city was Alexander Graham Bell born in 1847",
"Who composed the ballets Sleeping Beauty and The Nutcracker",
"AG Bell opened school in Boston in 1872 for Teachers of what",
"Benjamin Kubelsky 1894 fame as what comedian",
"In the Old Testament what book comes between Obadiah - Micah",
"Robin Williams dressed in drag for which 1993 film",
"Which chess piece could be a member of the church",
"Which German word means lightning war used in WW2",
"Broccoli belongs to what family of plants",
"Who designed the first Iron ship the Great Britain in 1845",
"Whose boat Bluebird was recently raised from Coniston water",
"in 1951 which (of two) car companies introduced power steering",
"Who wrote Catch 22 (both names)",
"Which country set up the world’s first chemistry lab in 1650",
"What links the names Botvinik, Tal, Karpov, Fischer",
"What is the national flower of Japan",
"Bombardier Billy Wells was seen on many Rank films - why",
"Where in France do claret wines come from",
"What did mathematician John Napier invent in 1614",
"What was the world’s first high level programming language 1957",
"Consumption was the former name of which disease",
"Which American state is nicknamed The Diamond State",
"What are the Sirocco, Mistral and Chinook",
"Who wrote about Willie Wonka and the Chocolate Factory",
"Who, at USA customs declared, nothing but my genius",
"Issur Danielovitch became famous a who",
"Who sailed in the Golden Hind",
 "What was the name of the plantation in Gone with the Wind",
"Who won the 1988 Superbowl",
"Which group believes in The Great Architect of the Universe",
"Robert Alan Zimmerman real name of who",
"Processed Galena produces which metal",
"Who wrote Gulliver’s Travels (both names)",
"What is a Ha Ha",
"In Japan what is Seppuku",
"Who discovered blood circulation",
"The dunnock is another name for which common bird",
"If someone said they were from Hellas - which country",
"Who was the son of Zeus and Maia - Gods Messenger",
"Roy Scherer jr became famous as who",
"Who wrote Brave New World (full name)",
"What links Calabria, Liguria, Puglia and Veneto",
"Which city in Rajasthan has riding breeches named after it",
"Portugal has had six Kings with what first name",
"What martial arts name means gentle way",
"Jean Claude Killy famous in which sport",
"Kimberlite contains what precious item",
"Who directed Dr Strangelove  -  2001 - The Shining (full name)",
"Rene Lalique - Art Nouveau designer worked what material",
"Who created the children's land of Narnia and Lion Witch Wardrobe",
"What animal lives in a drey",
"Why is Louise Brown - born 1978 famous",
"The title of whose book translates as my struggle",
"Anna Mary Robinson - famous American painter - what name",
"In which country would you find the Negev desert",
"Which character has been played by the most actors",
"In Greek mythology a Hamadryads spirit guarded what",
"Jocasta was the wife of Laius and the mother of who",
"Who wrote The Rights of Man - and The Age of Reason",
"What is the capital of Sicily",
"What was invented by Dr Edward Land in 1947",
"Syd Barett, Roger Waters, Richard Wright, Nick Mason - Group",
"Carlo Collodi created which famous children's character",
"What is mainly extracted from pitchblende",
"Which connects Delft, Sevres, Wedgwood, Chelsea",
"Which country introduced the worlds first diesel loco in 1912",
"in 1656 Christian Huygens invented what type of timekeeper",
"Duvali, Dushira and Holi are religious days in which religion",
"In what industry did John Davidson Rockefeller get rich",
"The Mau Mau were terrorists in which country late 50s early 60s",
"What movie cast included James Garner, Richard Attenbourough, Steve McQueen, Charles Bronson, Donald Pleasance, James Coburn, Gordon Jackson, Angus McPhee among many others",
"If you suffer from epistaxis what is wrong",
"In which book would you find the manservant Pas Partout",
"What animals name translates as water horse",
"In Greek mythology who killed the Gorgon",
"Which two metals are alloyed to make pewter",
"In 1899 the Eastman company in the USA produced first what",
"What links - Sarte, Neitzsche, Russell and Decartes",
"In 1643 Evangalisa Torichelli invented the first what",
"Which Spanish painter has first exhibition at 16 - also 4 year blue",
"Where did the mutineers of the Bounty settle",
"What movie cast included James Garner, Richard Attenbourough, Steve McQueen, Charles Bronson, Donald Pleasance, James Coburn, Gordon Jackson, Angus McPhee among many others",
"If you suffer from epistaxis what is wrong",
"In which book would you find the manservant Pas Partout",
"What animals name translates as water horse",
"In Greek mythology who killed the Gorgon",
"Which two metals are alloyed to make pewter",
"In 1899 the Eastman company in the USA produced first what",
"What links - Sarte, Neitzsche, Russell and Decartes",
"In 1643 Evangalisa Torichelli invented the first what",
"Which Spanish painter has first exhibition at 16 - also 4 year blue",
"Where did the mutineers of the Bounty settle",
"What is the longest river in Italy",
"What does a polyandric women have more than one of",
"What links Brazil, Uruguay, Mozambique and Angola",
"What is the American equivalent of the Irish Poteen",
"Who was the last king of Troy killed by Achilles son Pyrrhus",
"In 1911 the archaeologist Hiram Bingham discovered what lost city",
"Who won the Superbowl in 1989",
"Who wrote the book Billy Budd also Moby Dick",
"Which highwayman rode the horse Black Bess",
"Barry Allen was the alter ego of which DC comic superhero",
"In 1901 which brand of car was seen for the first time",
"Brisbane is the state capital of which SE Australian state",
"In Norse mythology what is the name of the ultimate battle",
"In 1890 the first electric what opened in London",
"Who wrote the children's novel Swallows and Amazons",
"Oil seed rape belongs to which plant family",
"Which Norwegian politicians name became a word for traitor",
"What is the capitol of Morocco",
"What shape were the sailors plates in Nelsons navy",
"What religion links Weasak, Dhrammacacka, and Bhodi day",
"Linus Torwalds invented and wrote what",
"The bander macaque has which commoner name",
"Zambia and Zimbabwe used to be called what",
"What is the staple food of one third of the worlds population",
"Paul Robeson the singer of old man river had what profession",
"Rene Laennac invented which aid for doctors in 1810",
"Jagger, Richards, Wyman, Jones, Watts, Stewart - which band",
"What digit does not exist in Roman Numerals",
"Who was nicknames The desert Fox (both Names)",
"What aid to archaeologists from 197 bc was found in Egypt 1799",
"Which annual sporting event between 2 teams started in 1829",
"Who was the jeweller to the Russian Court famous Easter eggs",
"What type of food is Taramasalata",
"What links Samuel Delaney, Fredrick Pohl, Harlan Ellison",
"Randolph Crane became famous as which cowboy actor",
"Ageusia is the loss of which sense",
"Which Irish political parties name translates as we ourselves",
"Henry Ford used assembly line in 1908 but someone before 1901",
"Who performed the first heart transplant in South Africa",
"What is the common name for the star Sirius",
"What calculating aid was invented by William Oughtred in 1662",
"Which Athenian philosopher wrote nothing - immortalised by Plato",
"Who designed the WW 1 plane Camel and co designed Hurricane",
"Crazy Horse and Sitting Bull were born in which US state",
"In 1666 Jesuit Bark was used as a prevention against what",
"In 1971 which USA space probe was first to orbit another planet",
"What links Catalonia, Andalusia, Cantabria, Galicia",
"Ingemar Stenmark won record 85 world cup races in what sport",
"Who wrote the music for the ballets Firebird and Rites of Spring",
"What common legal item literally means under penalty",
"Who was the only person to win world titles on bikes and cars",
"What is  the oldest swimming stroke",
"Which European country is divided into areas called Cantons",
"Which medical tool was developed by Sanctorius in 1612",
"What weapon was invented by Ernest Swinton used in 1916",
"Which mythological King chained grapes rose water fell",
"Who created Tarzan (all names) in 1914",
"Camellia Sinesis evergreen shrub better known as what",
"In 1901 who first transmitted radio signals across Atlantic",
"Who won six consecutive Wimbledon titles in the 1980s",
"What Italian building material translates as baked earth",
"What links Buddy Holly, Lyndon Johnston, Janice Joplin",
"Which eponymous character was Thane of Cawder Glaimes",
"Who wrote the 39 steps (both names)",
"Who won the Superbowl in 1987",
"What is the food tofu made from",
"Who was the son of Poseidon and Ampherite",
"Annie Mae Bullock became famous under which name (both)",
"What linked Armenia, Georgia, Latvia and Moldavia",
"What is the state capitol of New Jersey",
"Who won an Oscar for best supporting actor in Spartacus 1960",
"What was invented by James Dewer in 1872",
"Who was the Roman goddess of the hearth",
"Viticulture is the growing of what plants",
"In 1953 what was first successfully transmitted in the USA",
"Who wrote the Thin Man in 1934 (both names)",
"Angel falls Venezuela Highest but where second Highest",
"Whitcome Judson in 1891 invented what for fastening shoes",
"Who sold Louisiana to the USA in 1803",
"Gregory Pincus, John Rock, Gerhart Domangk developed what",
"The Gloucester E 28/39 first flew in 1941 - what was unusual",
"Women compete between USA and UK in Wightman Cup - Sport",
"Woolworth's - the 5 /10 cent store started in which us state 1979",
"Which actress starred in the original King Kong in 1933 (both)",
"Except Australia 1 New Zealand 1 USA  all since 1870 want?",
"What's missing from ale that’s included in beer",
"Until 1971 what was the name of Zaire",
"Karl Lienstater discovered which medical breakthrough in 1901",
"Who is the only American president elected unopposed",
"Which countries men use the most deodorant",
"Who played Billy the Kid in The Left Handed Gun",
"What was the first credit card",
"What links Humphry Davie, Michael Faraday, Madam Curie",
"Hippophagic society members support what",
"What did Britain swap Havana for with Spain in 1763",
"What is the crime of embracery",
"Which country made the worlds first feature film in 1906",
"Who wrote Gentlemen Prefer Blonds",
"What was Norman Bates hobby in Psycho",
"What was Casanovas day job",
"Where is the worlds largest gold depository",
"Why did the state of Indiana ban Robin Hood in 1953",
"Angelo Scicilano better know as who",
"How did George II die",
"What did Marlon Brando and George C Scott refuse",
"Why was convict 2599 unusual in Pen State prison 1924",
"What is 6 inches bigger in Summer",
"What two ingredients make the dish angels on horseback",
"What was Charles Dickens last (unfinished) novel",
"Which sea on Earth has no beaches",
"Reuben Tice died trying to invent a machine to do what",
"De Witt Wallace founded what",
"Who is the Patron Saint of thieves",
"According to his business card what job did Al Capone do",
"Humans are 10,000 times more sexually active that what animal",
"Shirley Schrift became famous as which actress",
"In Kansas what can a waiter not do in a teacup (legally)",
"Which country has the smallest birth rate",
"Which 1956 film caused riots in cinemas",
"Who did the USA buy the Virgin islands from",
"Who played the scarecrow in the Wiz (all black wiz of oz)",
"What was or is a Waltzing Mathilda",
"Which country was the first to introduce old age pensions",
"Which hats became popular with children in 1956",
"Malden Serkiovitch famous as which actor",
"What is it illegal to pawn in New York",
"What hospital did Dr Kildare work at",
"Collective nouns - a smuck of what",
"Who was Cleopatra's first husband",
"Who was John Dawkins better known as",
"Which film star has his statue in Leicester Square",
"Virginia McMath became famous as which actress",
"What is the name of Captain Ahab's ship",
"Roosevelt won the 1932 election - who lost it",
"Who wrote The History of Mr Polly",
"What is the first day of Lent",
"Mr Chips said goodbye - from which fictional school",
"Who buried the treasure on Treasure Island",
"Which TV series was narrated by Walter Winchell",
"In which country was Auschwitz",
"What was the first British instrumental to top the USA charts",
"On which national flag is there an eagle and a snake",
"What group of animals would be in a clowder",
"What is a Sam Browne",
"What is the chemical symbol for tungsten",
"Who are the two most translated English writers",
"Citius Altius Fortius is the motto of what organisation",
"What is the main ingredient of sauce Lyonnaise",
"Who played Miss Marple in 6 films (both names)",
"From what language does the word alphabet come",
"In the nursery rhyme what is Fridays child",
"What was the first film made in cinemascope",
"Where was the battle of Hastings fought",
"A pearmain is what type of fruit",
"What colour is the bull on an archery target",
"What was the Rolling Stones first no 1 hit",
"Name both rival gangs in West Side Story",
"In golf what do the Americans call an albatross",
"Which classical composer wrote the Hungarian Rhapsody",
"When is St Swithens day",
"What are ceps morels and chantrelles",
"Which part of his body did Charlie Chaplin insure",
"In golf what would you put in your shag bag",
"A bind is a group of what type of fish",
"Which author created Fu Manchu",
"Mrs Darell Waters (translated 128 languages) pen name",
"Who played the pawnbroker in the film of that name",
"What was the first manufactured item to be sold on Hire Purchase",
"Which letters denote Jesus Nazareth King of the Jews",
"In France if you were served le miel what would you eat",
"The Greek for circle of animals gives it name to what",
"Who was the Roman god of agriculture",
"What is ikebana",
"What nationality was Morse inventor of the famous code",
"Goa used to be a colony of which nation",
"What does a galactophagist drink",
"What did God create on the fifth day (both)",
"Where was Bob Dylan born",
"In the 18th century what would a pencil be",
"Agrippa poisoned her husband/uncle who was he",
"Who was the mother of Castor and Pollux",
"What are the snaffle Pelham and Weymouth",
"Walter Koenig played which part in the Star Trek series",
"Who had a hit with Devil Woman",
"What were the first false teeth made from",
"The jealous Athena turned who into a spider",
"What was the first Carry On film",
"Who was the female lead in The Shootist",
"What is a dzo",
"Hypermetropic people are what",
"Which leader lives in the Potola",
"What wood was the cross supposed to be made of",
"Joseph Levitch became famous as who",
"If you planted a bandarilla what are you doing",
"What was the first Pink Floyd album",
"in which city was the first public opera house opened",
"In what Elvis film did he play a double role",
"The Aphrodite of Melos has a more famous name - what",
"Which country invented the concentration camp",
"John Huston scored a hit with his first film  -  what?",
"Stan laurel, Mickey Rooney, Lana Turner what in common",
"What real person has been played most often in films",
"Scotopic people can do what",
"What is the most critical thing keeping bananas fresh transport",
"What is the name of the Paris stock exchange",
"Whose music featured in The Clockwork Orange",
"What was the Troggs most famous hit",
"In Japan what colour car is reserved for the royal family only",
"What city has Kogoshima as its airport",
"What was gangsters George Nelsons nickname",
"Whose first wife was actress Jayne Wyman",
"In MASH what is Radars favourite drink",
"What do you give on the third wedding anniversary",
"What is a baby whale called",
"In which film did the Rolls Royce have the number plate AU1",
"Vladamere Ashkenazy plays what musical instrument",
"With which organ does a snake hear",
"On what is the Mona Lisa painted",
"What is the second most common international crime",
"Count de Grisly was the first to perform what trick in 1799",
"Who wrote Les Miserable",
"Which bird turns it head upside down to eat",
"The colossus of Rhodes was a statue of who",
"Who rode a horse called Bucephalus",
"To which London club did Mycroft Holmes belong",
"What did William Addis invent in prison ",
"What is the only duty of police Gracthenvissers in Amsterdam",
"Kleenex tissues were originally intended as what in 1915",
"Who invented popcorn",
"What is the colour of mourning in Turkey",
"For what is spirits of salt another name",
"Which game is played on an oval with 18 player per team",
"In the Winnie the Pooh stories what is Kanga’s baby called",
"Which actor is common to Magnificent 7 and Dirty Dozen",
"Who saved Andromeda from the sea monster",
"What flower is the symbol of secrecy",
"What  item were originally called Hanways",
"What is Brussels best known statue",
"in which language does God Jul mean happy Xmas",
"Which flying pioneer was nicknamed the lone eagle",
"Horse statue - mounted man - on two legs  - how man die",
"Which American state produces the most potatoes",
"Who wrote Dr Zhivago",
"Who is Charlie Browns favourite baseball player (fictional)",
"Emerald is the birth stone for which month",
"Whose yacht was called Honey Fitz",
"What is the white trail behind a jet plane made from",
"What Italian habit did Thomas Coyrat introduce to England 1608",
"Purl Plain Fisherman's Cable types of what",
"Why was Mary Mallen locked up from 1915 to 1938",
"If you were doing vaccimulgence what doing",
"For what purpose was the chow chow dog originally bred",
"What kind of fruit is a kumquat",
"Who was the Greek goddess of love",
"What first appeared in New York World 21st December 1913",
"Which group of animals are called a cete",
"Which herb did the Romans eat top prevent drunkenness",
"What is the original literal meaning of the word bride",
"Who ran the first marathon",
"What is the only creature that can turn its stomach inside out",
"What is Milan's opera house called",
"What is the oldest most widely used drug on earth",
"What type of animal is a Samoyed",
"In which country did draughts (checkers) originate",
"Shane Fenton became famous as who",
"What is the worlds most popular green vegetable",
"What does a racoon do before eating its food",
"What other name is used for the snow leopard",
"Which drink did Bach enjoy so much he wrote a cantata for it",
"Who invented the first safety razor in 1895",
"What nationality is Thor Heyerdahl",
"What 3 ingredients make a sidecar cocktail",
"A spunder or drift is the name for a group of what animals",
"What is Erse",
"On oometer measures what",
"What did table tennis balls used to be made from",
"If you had variola what disease have you got",
"Which playing card is called the Curse of Scotland",
"Which painter did Hans van Meegeren most fake",
"Which country had the first women MPs 19 in 1907",
"In 1969 what category was added to the Nobel prizes",
"In which city was Bob Hope born",
"In the human body where is your occiput",
"Who wrote the Star Spangled Banner",
"Which food did Victorians deride as little bags of mystery",
"Which actor was dubbed the muscles from Brussels",
"Which film star was the first to appear on a postage stamp",
"What would you expect to find in a binnacle",
"Which Hollywood star has made the cover of Life most times",
"Which Mediterranean countries orchestra is bigger than its army",
"What links stags tails, pickled worms, gallstones, tomatoes",
"Baked beans were originally served in what sauce",
"Where can you buy a copy of Penguin News",
"Who was the hero of the old TV cop series Dragnet",
"Which African country was founded by Americans",
"What was Britain called - before it was Britain",
"What part of a frog do you rub to hypnotise it",
"How did multi millionaire Russell Sage save money",
"How was USA president James Buchanan different from all rest",
"What's involved in 20% of car accidents in Sweden",
"What's unusual about evangelist Amy Semple McPhersons coffin",
"Who would use a swozzle",
"What does a tailor do with his plonker",
"Churches in Malta have two what",
"Marnie Nixon what Deborah Kerr Natilie Wood Audrey Hepburn",
"Which Italian tractor maker tried making cars in 1960s",
"What first appeared on Page 1 of the Times 3 May 1966",
"Caruso put what in Nellie Melbas hand singing tiny hand frozen",
"What would you do with an Edzell blue",
"In what month did the Russian October revolution take place",
"Nobody's perfect is the last line in which classic comedy film",
"How did Buffalo Bill stick to one glass whisky a day",
"In 1760 what means of personal transport was invented",
"What three counties were Eliza Dolittle taught to pronounce",
"In Hitchcock's film The Trouble with Harry - what was the trouble",
"What was the first gramophone record made from",
"What did George Washington soak his wooden teeth in for taste",
"George V1 Mozart Al Jolson Casanova - which organisation",
"Who said 'Its so long since sex I forget who gets tied up'",
"St Appolonia Patron Saint of what",
"What is measured on the Gay-Lussac scale",
"A squid found in New Zealand had the biggest what ever seen",
"What was the first country to guarantee freedom of worship",
"which famous person invented the cat flap",
"By law what can you not do in Minnesota with your washing line",
"Why do Tibetans grow long nails on little fingers",
"Richard Penniman became famous as who",
"What is a snood",
"Who said 'men are creatures with two legs and 8 hands'",
"Which European country eats the most breakfast cereal",
"Philosopher Jeremy Bentham has a very unusual pet  - what",
"What country did Italy invade in 1935",
"Who sang the title song in the film Grease",
"What is produced in a ginnery",
"What was made illegal in England in 1439",
"What was invented by Dr Albert Southwick in 1881",
"In which country are you most likely to die from a scorpion sting",
"Who is the most filmed author",
"Excluding religious works what is the worlds top selling book",
"Who sold the most albums on a single day",
"What was the last item shown on British TV before WW2",
"What countries people had the longest life expectation",
"Who said 'I like Beethoven especially the poems'",
"What does the entire economy of the island of Nauru depend on",
"John Glen first USA to orbit earth was in which service",
"Oedipus was named after what - literal translation",
"What fish can hold objects in its tail",
"Who is the most filmed comic strip character",
"Whose version of A View to a Kill reached 1 in USA 2 in UK",
"Which country grows the most potatoes",
"What does a drosomoter measure",
"Which English Kings armour has the biggest codpiece",
"Which country was the first to abolish capitol punishment 1826",
"In law what is a co-parcener",
"Which pop group had a hit with Silence is Golden",
"Greek mathematician cylinder enclosed sphere carved on grave",
"What does a psephologist study",
"Where would you  find line of Mars - Girdle of Venus",
"British call this bird species tits - what do Americans call them",
"Which country owns the Hen and Chicken islands",
"Who created the TV series - The man from UNCLE",
"Which film director described actors as cattle",
"Shirley Bassey sang three Bond themes - which 3 films",
"Barring rain - in which athletics event would you get wet",
"What colour is the flesh of the Charentais melon",
"Who appeared on the first US postage stamps (both names)",
"Who  was the first person elected to US swimming hall fame",
"The guillotine was invented for chopping off what",
"Which country invented the bedsprings",
"Whets the difference between fog and mist",
"What did Spanish scientists fit to cows to increase milk yield",
"What people founded cheese making in England",
"What is the first name of Mr Toad - in Toad of Toad Hall",
"Atephobia is a fear of what",
"What are Grapnel, Bruce, Danforth, Plough types of?",
"Why did Handel compose The Messiah",
"Red flags flown by French ships - Joli Rouge origin of what name",
"in which country could you spend a Kwanza",
"John Henry Deutchendorf famous as who (both names)",
"Mitre Dovetail Jig and Hack are types of what",
"Tracey and Hepburn first film in 1942 was what",
"Antimacassars were fitted to chairs - what is macasser",
"Jack Ketch 1663 1686 had what job",
"Nekal was the first type of what product (Germany 1917)",
"Who was the first Grand Prix driver to used a safety belt in 1967",
"The SF award the Hugo is named after Hugo who?",
"Maurice Micklewhite became famous as who",
"What do Ombrophobes fear",
"If you had a Brassica Rapa what vegetable would you have",
"Boob Day in Spain is what day in Britain (practical jokes played)",
"What crime did Theresa Vaughn commit 62 times in 5 years",
"Who sailed in a ship called Queen Ann's Revenge",
"Saponification is the process that makes what common product",
"Blue red green yellow four Olympic rings colour what's missing",
"Detective Philip Marlow smokes what brand",
"Who landed on Timor Island after being cast adrift",
"What is the more common name of the Chaparral Cock",
"In what language did St Paul write his epistles",
"Ian Fleming's house was called Goldeneye - which country",
"Alfred Schneider became famous as who",
"A C-Curity was the original name of what common object",
"Fidelity Bravery Integrity is which organisations motto",
"Who was the first black entertainer to win an Emmy award",
"Anthony Daniels played who in a series of films",
"Of what material was the hairspring made in early watches",
"In 1860 Napoleon III banquet - serving dishes dearer gold - what",
"Which author created Dick Tracy",
"What is the worlds most widely used vegetable",
"What are lentigines",
"What type of animal is a vmi-vmi",
"What did Mege-Mouries invent in 1870 winning a Napoleon prize",
"What was Walt Disney's middle name",
"Who would you expect to find in Castle Gondolofo",
"What two items make up the dish devils on horseback",
"What does ludo mean (literally)",
"The Detours changed to The High Numbers then what name",
"What animal was believed to be a cross camel - leopard",
"An elephant has 400000 what in its trunk",
"What colour is cerulean",
"Who composed the Air for the G string (init and name)",
"What were Twinkletoes - Lucky Jim (stuffed cats) first to do",
"What are kreplach",
"The pica pica is what common bird",
"What male human feature was taxed in Elizabethan times",
"Which record company rejected the Beatles as being past it",
"From which country does spinach originate",
"British policemen have truncheons what is USA equivalent",
"In DC comics Linda Lee Danvers is whose alter ego",
"In what country does the cow tree grow - sap looks tastes  milk",
"The penny black - worlds first stamp  -  what was second",
"Which country produces Tokay",
"Where could you legally flash your dong  - then spend it",
"The Bald Eagle is Americas bird  -  What is Britain's",
"Australian Clement Wragge instituted what",
"What does Zip stand for in the American Zip Code",
"What wood is plywood mostly made from",
"What is a Hummum",
"In which sport are left handed people banned from playing",
"What food was invented in a sanatorium in 1890",
"What is a Bellwether",
"What was Procul Harem's greatest hit",
"Percy Shaw invented what in 1934",
"What animal produces its own sun tan lotion",
"What was a Nuremberg egg",
"What was the name of Isaac Newton's dog - caused fire in lab",
"Who was eaten by dogs in the Old Testament",
"In literature who is the alter ego of Percy Blakney",
"Juglans Regia is the real name of what type of nut tree",
"What album cover (by the Rolling Stones) had a zip on the side",
"What lives in a holt",
"Who is the Patron Saint of dancers and actors",
"What is the worlds tallest grass",
"Who owned the newspaper in Lou Grant - Nancy Marchand",
"Who reputedly first said - if in doubt tell the truth",
"John Richie became famous under what name",
"In Greek mythology who rowed the dead across the river Styx",
"Alfred White was a famous author under which name",
"Which acid was first prepared from distilled red ants",
"Who invented doctor Who",
"What took place on London's serpentine first time 16 June 1930",
"Which European city was the bride of the sea",
"Who (not Peter Sellers) played Inspector Clouseau in 1968",
"Where could you find the Lutine Bell",
"Yabusame is the Japanese version of what sport",
"Which Dickens novel is considered an autobiography",
"Dendrologists worship what",
"What is the national sport of Finland",
"Who was Agrippa's son",
"Peter Goldmak invented what in 1948",
"Milton lost which sense",
"What are camel haired brushes made of",
"How did the Greek dramatist Aeschalys die",
"Playing card - Raymond Shaw trance - Manchurian Candidate",
"Eiffel designed the Eiffel tower - what was his first name",
"The Salk vaccine is used against what disease",
"If you are born between June 23rd and July 23rd what star sign",
"An alloy of Iron - Chromium and Nickel makes what",
"Who said 'Public service is my motto'",
"Drakes Golden Hind was originally called what",
"In what film did Elvis play a Red Indian",
"What did the Victorians call servant regulators",
"Which country first used the fountain pen",
"What is the more popular name for the Londonderry Air",
"Freyr was the Norse god of what",
"TAP is the national airline of which country",
"In which country is the port of Frey Bentos",
"The Koh-i-Nor is a famous diamond - what does the name mean",
"A nilometer measures the rise and fall of what",
"What was Britain's first colony (annexed in 1583)",
"Joseph Lister - first operation antiseptic - 1867 on who",
"What was Black Beauties original name",
"Who was the original Peeping Tom looking at",
"What element is present in all organic compounds",
"What was Professor Moriarties first name",
"Who was known as the Little Brown Saint",
"Who rode a horse called Morengo",
"A skulk is a group of which animals",
"Who defended World heavyweight title twice on same night in 1906",
"What part of an aircraft is the empennage",
"We know who wrote Little Women but who wrote Little Men",
"Who was the Goddess of the rainbow",
"In European city can you be jailed for not killing furry caterpillars",
"Who was Olive Oyls boyfriend  -  before Popeye",
"Sienna law forbids women of what name from prostitution",
"What do the letters MG stand for on cars",
"Who was the first actor to appear on cover of Time magazine",
"Polyphemus was the leader of which group of mythical giants",
"What does a pluviomoter measure",
"Which game was illegal in Elizabethan England",
"What nationality was Oddjob",
"What is a Knout",
"What language has the most words",
"Which film star used to be a circus acrobat",
"The comma bacillus causes what disease",
"Which country invented Venetian Blinds",
"What is a quadriga",
"What is a brickfielder",
"Pupik means belly button in what language",
"What is the main ingredient in Borsch",
"What was the name of Dr Dolittle’s Parrot",
"What was the name of William Tells son (the apple head boy)",
"Laika was the first ever dog to do what",
"Where could you spend a Markka",
"What links a bick, throat, half swage, punching hole",
"The Fagus is the Latin name of what type of tree",
"If you have Chlorosis what colour does the skin go",
"The French say Bis - what word do the English use",
"Of what are Karakul, Texel, Romney Marsh types",
"What is biltong",
"What type of fish is Scomber Scombrus",
"What are brick, fontina, port salut, quargel types of",
"In which country did the turnip originate",
"Tchaikovsky died of which disease",
"Sam Barraclough owned which film star",
"Which animals can live longest without water",
"Captain Hanson Gregory Crockett created what void in 1847",
"Kaka means parrot in which language",
"Who wrote A Town Like Alice",
"Which fruit contains the most protein",
"Ignatius Loyola founded which organisation ",
"Which 16th century Italian wrote The Prince",
"A meander bend in a river, named from river meander - where",
"Who tells the story in The Arabian Nights",
"Alfred Jingle appears in which Dickens novel",
"Vaselina and Brillantino were alternate names which film",
"Chaplin ate a boot in the Gold Rush - what was it made of",
"Phoebe Anne Mozee better known as who",
"What is the tenth letter of the Greek alphabet",
"If you were misocapnic what do you hate",
"In sailing ship days who often acted as the ships doctor",
"An isoneph on a map joins places of equal what",
"Bumper Harris - wooden leg - what Job on London Underground",
"Who is Ivanhoe's wife",
"The Lent Lilly has a more common name - what",
"What would you be if you were a coryphée",
"Whose last words were - 'Clito I owe a cock to Asclepius'",
"What does the German word Panzer literally mean",
"What is Frances longest river",
"In which month is the Munich beer festival held",
"What was the name of Norse God Thor's hammer",
"Who ordered John the Baptists execution",
"What was Walt Disney's first cartoon character",
"What medication discovered in 1928 but introduced 1940",
"Who wrote Beau Geste",
"Prophesied the Chalus the Greek - Die on day - did of what",
"Who is Aladdin's father",
"What American state is the Badger state",
"Why was Fred Lorz disqualified 1904 Olympic marathon",
"In China what colour does the bride traditionally wear",
"A muster is a group of which birds",
"Bohea is a type of what",
"In which country were antibiotics first used",
"Which country grew the first Orange",
"Gossima was the original name of what game",
"Wild marjoram is also known as what",
"What was the name of Roses monkey in Friends",
"Horse brasses - on dreyhorses - originally what purpose",
"Alfred Hitchcock admitted to being terrified of what",
"What was the name of Sancho Panza's donkey",
"What is Steganography",
"An Albert chain is usually attached to what",
"An unkindness is a group of what birds",
"A fellmonger deals in what items",
"What colour habit do Franciscan monks wear",
"Nenen-Kona is sold in Russia - what do we call it",
"Hugh Lofting created which famous character",
"What was the name of Russian bear mascot 1980 Olympics",
"What ingredient must French ice cream contain by law",
"A kindle is the name for a group of what young animals",
"What is the commonest symbol on flags of the world",
"Which country is alphabetically last",
"Smiths Bon-Bons changed their name to what after 1840",
"Minerva is the Goddess of what",
"What type of animal is a jennet",
"If you were crapulous what would you be",
"Where would you Wedel",
"What is the correct name for a baby otter",
"What colour is the gemstone peridot",
"Sanskrit is an old language - what does the word mean",
"In which country do they play houlani - type of hockey",
"What does the name Tabitha mean",
"With what is spangy played",
"Where did Spam get its name",
"The Pogues took their name from Pogue Mahone - what mean",
"What comes after the year of the snake - Chinese calendar",
"Mosi-oa-Tunya - Smoke that Thunders - what natural feature",
"One person every 6 seconds dies from what",
"Approximately 40 million of what are consumed each year",
"What is the worlds largest rodent",
"Which winter game is known as the roaring game",
"The first known what happened in Wisconsin 1878",
"Which 2 countries will host the 2002 Soccer World Cup finals",
"In 1935 Charlton C McGee invented what in the USA",
"Which French philosopher created analytical geometry",
"The length of what is approximately 1/10th circumference of earth",
"What was the world's first computer bug in 1946",
"What does a polythesistic person believe in",
"Who founded the Greek theatre",
"Maria Magdelana Von Losch Beyyer know as who",
"If you suffered from tantartism what would you be doing",
"Which literary prize started in 1968",
"What links Fitzroy, Essenden, Collingswood and Carlton",
"What countries people spend most private money on recreation",
"What links The Reivers, Grapes of Wrath, Humboldt’s Gift",
"USA has most airports which country has second most",
"In 1829 Walter Hunt invented what common item",
"Fredrick Sanger discovered which medical life saver",
"Who invented punched cards used in early computing 1880s",
"Why did Roselin Franklin (pre discovered dna helix) no Nobel",
"What is a Dwarf Goby",
"What types can be saddle, plane or pivotal",
"1500 paces was what Roman measurement",
"Denis Gabor of Hungary 1971 Nobel prize for what invention",
"Who gave the UN the land in NY to build their HQ",
"In 1779 Abraham Darby built the worlds first what",
"What is the worlds oldest monotheistic religion",
"An aubade or alborda is a song - but what type",
"What sport links Castle Cup, Red Stripe Cup, Ranji Trophy",
"What countries leader does not have an official residence",
"Which writer coined the word Cyberspace in 1984",
"Demeter was the Greek god of what (Ceres Roman)",
"What film won the 1943 Oscar as best film",
"What do ungulate animals alone have",
"Dr Ludwig L Zamenhof invented what 1887 Poland",
"Who wrote The Picture of Dorian Grey in 1891",
"Who composed The Planets suit (both names)",
"What links Doric, Ionic, Tuscan, Corinthian and Composite",
"What is phonetic alphabet word for U",
"Why were women barred from original Olympic Games",
"In which USA state is Churchill Downs racetrack",
"In 1867 Lucian B Smith invented what restraint",
"In 1961 which Henry Mancini record won Grammy record of year",
"What links Willie Brant, Lech Walesa, Yasser Arafat",
"Which countries government spends most in social security %",
"Archaeopteryx was the first what",
"In 1810 in England Peter Durand invented what",
"Who was offered the presidency of Israel in 1952 (turned down)",
"What is the oldest known infectious disease",
"A JPEG is a picture file format - what does JPEG stand for",
"What is the worlds largest sea (in area)",
"Which islands wildlife is 90% unique",
"What are truffles - highly prized as food",
"Which Game is Played 15 a side and scores 3 or 1 points",
"What was invented in 1855 45 years later than it was needed",
"What links Sissinnius, Zosimus, Liberius, Sergius V1,Victor II",
"What is the world largest seed",
"Bristlemouths are the worlds most common what",
"What swims at 1/8 inch an hour",
"Trypanophobia is fear of what",
"Chogori is better know by what boring name",
"Colonel Jacob Schick invented what in 1928 in USA",
"What links Duke Wellington, Earl Derby, Marquis Salisbury",
"In 1996 which Celine Dion album Grammy album of year",
"What weight is the lightest in Amateur Boxing",
"Which country has the worlds biggest (on land) National Park",
"What language speakers were shot Russia and Germany 1930s",
"Ronald Ross campaigned for the destruction of what",
"Who won two Nobel prizes in different fields",
"Name 3rd cent BC Greek mathematician wrote The Elements",
"Evidence of what alternative treatment found in 5300 mummy",
"North Fork Roe River - worlds shortest - which US state",
"In 1879 James Ritty invented what",
"Who wrote the novel Tom Jones in 1749",
"What links Millionaires, Metropolitans, Black Hawks, Silver seven",
"What country - largest earthquake of 20th cent 8.6 Richter 1906",
"The okapi belongs to what family of animals",
"Dimitri Mendeleyev is credited with the discover of what",
"What feature of a triangle makes it scalene",
"Taphophobia is fear of what",
"In the Chinese New Year what year follows Rat",
"Genuphobia is the fear of what",
"Percy LeBaron Spencer invented what in 1945 in USA",
"St Peter was the first Pope - Who was second",
"What 1945 film won best picture, actor, director Oscars",
"What is the literal translation of pot-pouri",
"Who did James Bond marry - character - (both names)",
"What is studied in the science of somatology",
"What was Hugh Hefner's jet plane called",
"What profession did Handel originally study",
"What European nation was the first to drink tea",
"Beaufort - the wind scale man - had what job",
"What bird is the symbol of Penguin books (children's section)",
"Diane Leather was the first woman to do what",
"What is Admiral Sir Miles Messervy usually known as",
"Which part of the body is most sensitive to radiation",
"What film made 58 times - cartoon, porrno, operatic, ballet",
"Mr Chips said goodbye from Brookfield school - What subject",
"In which American city can you get doctorate in hambugerology",
"Which author created The Saint (both names)",
"What is sericulture",
"What was Edison’s first practical invention",
"Frigophobia fear of what",
"Which company invented the transistor radio in 1952",
"Who is the only solo performer to win Euro song twice",
"Franz Liszt was the farther in law of what composer",
"In what town was Leonardo Da Vinci born",
"Who directed the Halloween series of films",
"What metal impurity makes rubies red and emeralds green",
"Helen Mitchell became famous as what soprano",
"Robert Whithead invented what weapon in 1866",
"Zymase and Glucose combine to form what drug",
"Translated literally what does television mean",
"Not as soups what have gazpacho - vichyssoise in common",
"Who was the Greek goddess of retribution",
"47 people worked on a committee to produce what work",
"What book was made into the first feature length British cartoon",
"Who first said 'Publish and be Damned'",
"Edwin Drake sank the first of them in 1859 - what were they",
"Calico cloth was invented in which country",
"What is dittology",
"Who played Pink in the movie The Wall",
"Rhabdophobia fear of what",
"Dr C W Long was the first to use what (anaesthetic) in 1842",
"Hey Big Spender comes from what musical",
"Jamie Farr played what role in MASH",
"Whets the correct name for golf club called Texas Wedge",
"Whose nickname was slowhand (both names)",
"Which country invented the mariners compass",
"What countries international car registration letters are DZ",
"The name Malissa means what",
"What was Acadia",
"Dragoon, Antwerp, Poulter, Tumbler, Horseman types of what",
"What was the first frozen food available in Britain in 1937",
"If you suffer from cynanthropy what do you think you are",
"What is the phonetic alphabet word for letter P",
"What is a runcible spoon",
"The artist Abbott Thayer's developed what for military use",
"What did Francis Bacon call The Purest of Pleasures",
"What is the largest single known gold object in the world",
"Madame Pauline de Vere first female circus performer - do what",
"How was Alexander the Greats body preserved",
"Californian law no shooting any animal - moving car except what",
"Peter Falk plays Lt Colombo but who was first offered role",
"What type of birds (Hugin + Munin) sit on the shoulders of Odin",
"Where are you most likely to have a serious accident",
"Melvin R Bissell invented what in 1876 in the USA",
"Peniaphobia fear of what",
"About which game has most books been written",
"Albert De Salvo was better known as who",
"What was the last European nation to accept the potato",
"Students at Cambridge - no dogs - what Lord Byron keep",
"King Mongut had aprox 9000 wife's/concubines what country",
"Only approx one third worlds population uses what regularly",
"William Tayton was the first man to do what",
"Clemintina Campbell famous as who",
"What should you give after 15 years of marriage",
"What is a Charollais",
"What place is called Rapa-nui by its native inhabitants",
"Where was/is the original Penthouse",
"What pop group took their name from a Herman Hess novel",
"How often does a Hebdomadal Council meet",
"What was unusual about Tyrell's car in the 1976 Spanish G Prix",
"In what country is the Eucumbene Dam",
"Males outnumber females by 5 to 1 in what addiction",
"For what would an Edgar be awarded or won",
"What are salopettes",
"Which society cared - plague victims when physicians left 1665",
"Domenikos Theotocopoulos born Crete - died Spain - who");

$answers = array(
"Beach Boys",
"Five",
"Red",
"Albania",
"Green",
"Knee",
"Arizona",
"Vodka",
"Yuri Gagarin",
"Wear it",
"Judas Escariot",
"Duck billed platypus",
"Dolphin",
"John Lenon",
"Red Rum",
"Lee Majors",
"Sheep",
"Mekon",
"Robin (Batman and Robin)",
"Calling birds",
"The bush kangaroo",
"Tightrope walker",
"Gnasher",
"Camels",
"David Jason",
"Benny Goodman",
"Louis Bleriot",
"Sylvester Stallone",
"Crimean",
"John Logie Baird",
"Golfer",
"Sparrow",
"Lose their leaves in winter",
"Spoon",
"Dentist",
"Lady Chatterlys Lover",
"Plum",
"Six",
"The Producers",
"Douglas Bader",
"Admiral Benbow",
"Harry Houdini",
"Christopher Columbus",
"Napoleon Bonaparte",
"Margaret Mitchell",
"The Black Death",
"Pinocchio",
"Walt Disney",
"Eat porridge",
"Victoria Cross",
"Beards",
"Barrister",
"Bogart",
"Dolly Parton",
"International Monetary Fund",
"Thomas the tank engine",
"China",
"Microsoft",
"Eat it",
"Rick's",
"Casino Royal",
"Dog",
"Schilling",
"Red Crescent",
"Jack",
"He invented Dynamite",
"Roger Bannister",
"Mountains in Scotland",
"Toyota",
"Republic of Ireland or Eire",
"The Curies",
"Hair",
"John Constable",
"Number 13",
"Kit or Kitten",
"France",
"Harry Palmer",
"Brotherhood of Man",
"Turkey",
"Fish",
"Cigar",
"Ants",
"Sulphuric",
"Parliament",
"Hare",
"Doc Savage",
"Oliver Hardy",
"Fish",
"Blood Groups",
"Potato",
"Hamlin",
"Lourdes",
"Calcutta",
"Hovercraft",
"Scarecrow",
"Shoes",
"Toenails",
"German Measles",
"Talc",
"Mona Lisa",
"Puccini",
"India",
"George Orwell",
"Shoemaker",
"China",
"Barbara Stanwyck",
"Grenadine",
"Art of Dancing",
"Horses",
"Alexander Dumas",
"Hocus Pocus",
"Louis Bleriot",
"Dr No",
"Silence of the Lambs",
"Addis Ababa",
"Medicine",
"Motorcycle Racing",
"Alaska",
"Berlin MexicoLondon",
"Woody Allen",
"Amnesty International",
"Nelson Mandela",
"Tutankamen tomb",
"Pluto",
"Jackie Joyner-Kersey",
"Jayne Austin",
"Archimedes",
"Johan Sebastian Bach",
"Minnesota twins",
"Your Holiness",
"Edinburgh",
"Tchaikovsky",
"The Deaf",
"Jack Benny",
"Jonah",
"Mrs Doubtfire",
"Bishop",
"Blitzkrieg",
"Cabbage",
"I. Kingdom Brunel",
"Donald Campbell",
"Buick - Chrysler",
"Joseph Heller",
"Netherlands",
"Chess World Champs",
"Chrysanthemum",
"Hit Gong",
"Bordeaux",
"Logarithms",
"IBM FORTRAN",
"Tuberculosis",
"Delaware",
"Winds",
"Roald Dahl",
"Oscar Wilde",
"Kirk Douglas",
"Sir Francis Drake",
"Tara",
"Washington Redskins",
"Freemasons",
"Bob Dylan",
"Lead",
"Jonathon Swift",
"Sunken Fence",
"Hari Kari",
"William Harvey",
"Hedge Sparrow",
"Greece",
"Hermes",
"Rock Hudson",
"Aldus Huxley",
"Regions of Italy",
"Jodhpur",
"John",
"Judo",
"Skiing",
"Diamonds",
"Stanley Kubrick",
"Glass",
"Clive Staples Lewis",
"Squirrel",
"First test tube baby",
"Adolf Hitler",
"Grandma Moses",
"Israel",
"Sherlock Holmes",
"Trees",
"Oedipus",
"Thomas Paine",
"Palermo",
"Polaroid",
"Pink Floyd",
"Pinocchio",
"Uranium",
"Porcelain",
"Germany",
"Pendulum clock",
"Hindu",
"Oil",
"Kenya",
"The Great Escape",
"Nosebleed",
"Around the world in 80 days",
"Hippopotamus",
"Perseus",
"Tin and Lead",
"Kodak 1",
"Philosophers",
"Barometer",
"Pablo Picasso",
"Pitcairn Islands",
"The Great Escape",
"Nosebleed",
"Around the world in 80 days",
"Hippopotamus",
"Perseus",
"Tin and Lead",
"Kodak 1",
"Philosophers",
"Barometer",
"Pablo Picasso",
"Pitcairn Islands",
"Po",
"Husband",
"Colonies of Portugal",
"Moonshine",
"Priam",
"Machu Picchu",
"San Francisco 49 ers",
"Herman Melville",
"Dick Turpin",
"The Flash",
"Mercedes",
"Queensland",
"Ragnarok",
"Underground railway",
"Arthur Ransom",
"Mustard",
"Vidkun Quisling",
"Rabat",
"Square Thus Square meal",
"Buddhist",
"Linux computer operating system",
"Rhesus Monkey",
"Rhodesia",
"Rice",
"Lawyer",
"Stethoscope",
"The Rolling Stones",
"Zero",
"Erwin Rommel",
"Rosetta Stone",
"The University Boat Race",
"Faberge",
"Cured /smoked cod roe",
"Science Fiction",
"Randolph Scott",
"Taste",
"Sein Fein",
"Ransome Olds",
"Christian Barnard",
"Dog Star",
"Slide Rule",
"Socrates",
"Thomas Octave Murdoch Sopwith",
"South Dakota",
"Malaria",
"Mariner 9",
"Regions of Spain",
"Skiing",
"Igor Stravinsky",
"Subpoena",
"John Surtees",
"Breaststroke 16th century",
"Switzerland",
"Thermometer",
"Tank",
"Tantalus",
"Edgar Rice Burroughs",
"Tea",
"Marconi",
"Martina Navratilova",
"Terracotta",
"State of Texas",
"Macbeth",
"John Buchan",
"New York Giants",
"Soya Bean Curd",
"Triton",
"Tina Turner",
"USSR",
"Trenton",
"Peter Ustinov",
"Vacuum or thermos flask",
"Vesta",
"Vines",
"Colour Television",
"Dashiell Hammett",
"Yosemite USA",
"Zip Fastener",
"Napoleon",
"Oral Contraceptive",
"Whittle Jet Engine",
"Tennis",
"Pennsylvania",
"Fay Wray",
"America's Cup",
"Hops",
"Congo",
"ABO Blood Groups",
"George Washington 1798 1792",
"Japan",
"Paul Newman",
"Diners Club",
"Poisoned by chemicals work",
"Eating horsemeat",
"Florida",
"Jury Bribing",
"Australia Story of Kelly gang",
"Anita Loos",
"Stuffing birds",
"Librarian",
"Federal reserve bank Manhattan",
"Communist - rob rich",
"Charles Atlas",
"Fell off toilet",
"Oscars",
"Dog doing life for killing cat",
"Eiffel tower",
"Oysters - wrapped in Bacon",
"Mystery of Edwin Drood",
"Sargasso sea",
"Dewrinkle prunes",
"Readers Digest",
"St Nicholas",
"Sell second hand furniture",
"Rabbits",
"Shelly Winters",
"Serve wine",
"Vatican City",
"Rock around the clock",
"Denmark",
"Michael Jackson",
"Swagman's Knapsack",
"Germany",
"Davy Crocket",
"Karl Malden",
"American flag",
"Blaire General",
"Jellyfish",
"Ptolemy Dionysus",
"Artful Dodger",
"Charlie Chaplin",
"Ginger Rodgers",
"Peaquod",
"Herbert Hoover",
"H G Wells",
"Ash Wednesday",
"Brookfield",
"Captain Flint",
"The Untouchables",
"Poland",
"Telstar by The Tornados",
"Mexico",
"Cats",
"Military belt",
"W",
"Shakespeare - Agatha Christie",
"Olympic",
"Onions",
"Margaret Rutherford",
"Greek -alpha beta",
"Loving and Giving",
"The robe",
"Senlac hill",
"Apple",
"Gold",
"Its all over now",
"Sharks Jets",
"Double Eagle",
"Franz Liszt",
"15th July",
"Mushrooms",
"Feet",
"Practice Balls",
"Salmon",
"Sax Rohmer",
"Edith Blyton",
"Rod Stiger",
"Singer sewing machine in 1850s",
"INRI",
"Honey",
"Zodiac",
"Saturn",
"Flower arranging",
"American",
"Portugal",
"Milk",
"Sea creatures and birds",
"Duluth Minnesota",
"Brush",
"Claudius",
"Helen of Troy",
"Horse bits",
"Ensign Chekov",
"Cliff Richard",
"Ivory",
"Arachne",
"Carry on Sergeant",
"Lauren Bacall",
"Cow Yak cross",
"Long Sighted",
"Dalai Lama",
"Mistletoe",
"Jerry Lewis",
"Bullfighting",
"Piper at the gates of dawn",
"Venice",
"Kissing Cousins",
"Venus de Milo",
"Britain - Boer war",
"Maltese falcon",
"8 marriages",
"Napoleon Bonaparte",
"See in the dark",
"Temperature not below 13 C 55F",
"Bourse",
"Beethoven",
"Wild Thing",
"Maroon",
"Tokyo",
"Baby Face",
"Ronald Regan",
"Grape Knee High",
"Leather",
"Calf",
"Goldfinger",
"Piano",
"Tongue",
"Wood",
"Art theft",
"Saw woman in half",
"Victor Hugo",
"Flamingo",
"Apollo",
"Alexander the Great",
"Diogones",
"Toothbrush",
"Motorists in canals 39",
"WW1 Gas mask filters",
"American Indians",
"Violet",
"Hydrochloric acid",
"Australian football",
"Roo",
"Charles Bronson",
"Perseus",
"Rose",
"Umbrellas",
"The Mannequin Pis",
"Swedish",
"Charles Lindbergh",
"Killed in Battle",
"Idaho",
"Boris Pasternak",
"Joe Shlabotnik",
"May",
"John Fitzgerald Kennedy",
"Ice Crystals",
"Eating with forks",
"Knitting stitches",
"Typhoid Mary",
"Milking a cow",
"As food or Chow",
"Small Orange",
"Aphrodite",
"Crossword",
"Badgers",
"Parsley",
"To cook",
"Phidipedes",
"Starfish",
"La Scala",
"Alcohol",
"Dog",
"Egypt",
"Alvin Stardust",
"Lettuce",
"Washes it in water",
"Ounce",
"Coffee",
"King Camp Gillette",
"Norwegian",
"Brandy Cointreau Lemon juice",
"Swine",
"Irish Gaelic language",
"Birds Eggs",
"Cork",
"Smallpox",
"Nine of Diamonds",
"Vermeer",
"Finland",
"Economics",
"London (Eltham)",
"Back of head",
"Francis Scott-key",
"Sausages",
"Jean Claude Van Dam",
"Grace Kelly",
"Ships compass",
"Elizabeth Taylor",
"Monaco",
"Once thought to be Aphrodisiacs",
"Treacle - molasses",
"Falkland Islands",
"Sergeant Joe Friday",
"Liberia",
"Albion",
"Its belly",
"Not wear underwear",
"Batchelor maybe gay",
"A moose",
"Contains Telephone",
"Punch and Judy man",
"Press suits",
"Clocks right and wrong confuse devil",
"Dubbed in their singing voices",
"Lamborghini",
"News stories",
"Hot Sausage",
"Eat it",
"November",
"Some Like it Hot",
"Quart glass",
"Roller Skates",
"Hertford Hereford Hampshire",
"He was dead",
"Tinfoil",
"Port",
"Freemasons",
"Joan Rivers",
"Toothache",
"Alcohol strength",
"Eye 15.75 inches",
"Transylvania",
"Isaac Newton",
"Put male female washing together",
"To pick noses efficiently",
"Little Richard",
"A kind of hairnet",
"Jayne Mansfield",
"Britain",
"Tea Pot",
"Abyssinia",
"Frankie Valli",
"Cotton",
"Kissing",
"Electric chair",
"Mexico",
"Shakespeare",
"Guinness Book of Records",
"Elvis 20 million day after death",
"Mickey Mouse",
"Iceland",
"Ringo Starr",
"Bird shit",
"US Marine Corps",
"Swollen feet",
"Sea Horse",
"Zorro",
"Duran Duran",
"Russia",
"Dew",
"Henry 8",
"Russia Czar Nicholas",
"Joint Heir",
"Tremaloes",
"Archimedes",
"Voting - Elections",
"Palm",
"Chickadees",
"North island New Zealand",
"Ian Fleming",
"Alfred Hitchcock",
"Goldfinger ,Diamonds are Forever, Moonraker",
"Steeplechase",
"Orange",
"Washington - Franklin",
"Johnny Weismuller",
"Hands",
"Greeks",
"Seeing Distance under 1000yd",
"False Teeth",
"Romans",
"Thaddeus",
"Imperfection",
"Anchor",
"For Cash",
"Jolly Rodger",
"Angola",
"John Denver",
"Saw",
"Woman of the Year",
"Hair oil",
"Hangman",
"Detergent",
"Jackie Stuart",
"Gernsbeck",
"Michael Caine",
"Rain",
"Turnip",
"April Fools Day 1st April",
"Bigamy",
"Blackbeard",
"Soap",
"Black",
"Camels",
"Captain Bligh",
"The Road Runner",
"Greek",
"Jamaica",
"Lenny Bruce",
"Zip Fastener",
"FBI",
"Harry Bellefonte",
"C-P3O",
"Pigs Hair",
"Aluminium",
"Chester Gould",
"Onion",
"Freckles",
"Very small pig",
"Margarine",
"Elias",
"The Pope",
"Bacon Prunes",
"I Play",
"The Who",
"Giraffe",
"Muscles",
"Deep Blue",
"JS Bach",
"Fly across Atlantic Alcock Brown",
"Jewish ravioli",
"Magpie",
"Beards",
"Decca",
"Iran",
"Nightstick",
"Supergirl",
"Venezuela",
"Two penny Blue",
"Hungary",
"Vietnam currency",
"Robin",
"Naming Hurricanes",
"Zone Improvement Plan",
"Birch",
"Turkish bath",
"Polo",
"Kellogg corn flakes",
"Leader of flock of sheep",
"Whiter shade of pale",
"Cats eyes",
"Hippopotamus",
"Pocket watch / clock",
"Diamond",
"Jezebel",
"Scarlet Pimpernel",
"Walnut",
"Sticky Fingers",
"An Otter",
"St Vitas",
"Bamboo",
"Mrs Pyncheron",
"Mark Twain",
"Sid Vicious",
"Charon",
"James Herriot",
"Formic acid",
"Terry Nation",
"Mixed Bathing",
"Venice",
"Alan Arkin",
"Lloyds of London",
"Archery",
"David Copperfield",
"Trees",
"Motor Rallying",
"Nero",
"LP record",
"Sight",
"Squirrels tails",
"Eagle dropped tortoise on head",
"Queen Diamonds",
"Gustave",
"Polio",
"Cancer",
"Stainless Steel",
"Al Capone",
"The Pelican",
"Stay away Joe",
"Alarm Clocks",
"Egypt",
"Danny Boy",
"Fertility",
"Portugal",
"Uruguay",
"Mountain of Light",
"Rivers (originally Nile)",
"Newfoundland",
"His sister",
"Darkie",
"Lady Godiva",
"Carbon",
"James",
"Ghandi",
"Napoleon at Waterloo",
"Foxes",
"Tommy Burns - both 1st KOs",
"Tail Unit",
"Lousia May Alcott",
"Iris",
"Brussels",
"Ham Gravy",
"Maria",
"Morris Garages",
"Charlie Chaplin",
"Cyclops",
"Rainfall",
"Bowls",
"Korean",
"Russian flogging whip",
"English",
"Burt Lancaster",
"Cholera",
"Japan",
"Roman 4 horse chariot",
"Hot SE Aussie wind",
"Yiddish",
"Beetroot",
"Polynesia",
"Walter",
"Go into space",
"Finland",
"Anvil they are parts of it",
"Beech",
"Green",
"Encore",
"Sheep",
"Dried meat",
"Mackerel",
"Cheese",
"Greece",
"Cholera",
"Lassie",
"Rats",
"Hole in Doughnuts",
"Maori",
"Nevil Shute",
"Avocado",
"Jesuits",
"Machiavelli",
"Turkey",
"Sheherazade",
"The Pickwick Papers",
"Grease",
"Liquorice",
"Annie Oakley",
"Kappa",
"Tobacco Smoke",
"Cook",
"Average Cloud Cover",
"Ride new escalators",
"Rowena",
"Daffodil",
"Ballet Dancer",
"Socrates",
"Armour",
"Loire",
"October",
"Mjolnir",
"King Herod",
"Oswald the Rabbit",
"Penicillin",
"P C Wren",
"Laughing cos he was not dead",
"Mustapha the tailor",
"Wisconsin",
"Hitched a lift passing car",
"Red",
"Peacocks",
"Tea",
"Egypt",
"China",
"Table Tennis",
"Oregano",
"Marcel",
"Charms",
"Policeman",
"Dapple",
"Invisible ink writing",
"Watch",
"Ravens",
"Animal skins",
"Grey",
"Pepsi-Cola",
"Doctor Dolittle",
"Mischa",
"Eggs",
"Kittens",
"Star",
"Zimbabwe",
"Christmas Crackers",
"Wisdom",
"Small Spanish horse",
"Drunk",
"Ski slope",
"Kitten",
"Green",
"Put together",
"Turkey",
"Gazelle",
"Marbles",
"Spiced Ham",
"Kiss my arse",
"Horse",
"Victoria falls",
"Contaminated water diseases",
"Bananas",
"Capybara",
"Curling",
"Organised motor race",
"Japan - South Korea",
"Parking Meter",
"Rene Decartes",
"Great wall of China",
"A moth",
"Many Gods",
"Thespis",
"Marlene Dietrich",
"Dancing Mania",
"Booker McConnell",
"Aussie rules football teams",
"Taiwan's",
"Pulitzer Prize winners",
"Australia",
"Safety Pin",
"Insulin",
"Herman Hollerith",
"She was dead",
"Worlds smallest true fish",
"Body Joints",
"League",
"Holograms",
"John D Rockerfeller",
"Metal Bridge",
"Judaism",
"Mourning",
"Cricket",
"Cuba",
"William Gibson - Neuromancer",
"Harvest",
"Casablanca",
"Hooves",
"Esperanto",
"Oscar Wilde",
"Gustav Holst",
"Classical Architecture",
"Uniform",
"Male entries nude",
"Louisville Kentucky",
"Barbed Wire",
"Moon River",
"Nobel Peace Prize",
"Uruguay",
"Bird",
"Tin can",
"Albert Einstein",
"Leprosy",
"Joint Photographic Experts Group",
"South China",
"Madagascar",
"Fungi",
"Gaelic Football",
"Can Opener",
"Popes",
"Coco-de-mare palm - double coconut",
"Fish",
"Sperm",
"Inoculations - Injections",
"K2",
"Electric Razor",
"UK Prime Ministers",
"Falling into You",
"Light Flyweight",
"Canada",
"Esperanto",
"Mosquitoes",
"Marie Curie Physics 1903 Chemistry 1911",
"Euclid",
"Acupuncture",
"Montana",
"Cash Register",
"Henry Fielding",
"Stanley Cup winners Ice Hockey",
"Colombia",
"Giraffe",
"Periodic Table",
"Different side lengths",
"Buried Alive",
"Ox",
"Knees",
"Microwave Oven",
"St Linus",
"The Lost Weekend",
"Putrid Pot",
"Theresa Draco",
"The Body",
"Big Bunny",
"The Law",
"The Dutch",
"Sailor",
"Puffin",
"Sub 5 minute mile",
"M",
"The Blood",
"Cinderella",
"Latin",
"Hamburger College - Chicago",
"Leslie Charteris",
"Growing Silkworms",
"Tick a Tape for stockmarket",
"Being Cold",
"Sony",
"Johnny Logan 1980 - 1987",
"Richard Wagner",
"Vinci",
"John Carpenter",
"Chromium",
"Nellie Melba",
"Torpedo",
"Alcohol",
"Far Seeing",
"Served Cold",
"Nemesis",
"Authorised version of Bible",
"Animal Farm in 1954",
"Wellington re Harriot Wilson mistress",
"Oil Wells",
"India",
"Double meaning",
"Bob Geldorf",
"Being Beaten",
"Ether",
"Sweet Charity",
"Corporal Clinger",
"Putter",
"Eric Clapton",
"China",
"Algeria",
"Bee",
"Nova Scotia",
"Pigeon",
"Asparagus",
"Dog",
"Papa",
"A broad Pickle fork",
"Camouflage colours",
"The Garden",
"Tutankhamens Coffin",
"Head in Lions Mouth",
"In large jar of honey",
"Whale",
"Bing Crosby",
"Ravens",
"In your home",
"Carpet Sweeper",
"Being Penniless",
"Chess",
"The Boston Strangler",
"France",
"Bear",
"Siam - Thailand",
"Fork",
"Appear on TV",
"Cleo Lane",
"Crystal",
"Type of Cattle",
"Easter Island",
"In a Real Tennis Court",
"Steppenwolff",
"Weekly",
"Six Wheels",
"Australia New S Wales",
"Alcoholism",
"Mystery Writing",
"Snow proof Dungaree trousers",
"Apothecaries",
"El Greco");




















function drawHeader()
{
	echo "<div align=\"center\"><h1>QuizB0t!</h1><br>Can you beat the 1000 questions?<br>Score: " . $_SESSION['score'] . "&nbsp;&nbsp;&nbsp;(<a href=\"index.php?resetscore\">Reset progress</a>)<br></div>\n";
}












//vars
if(!isset($_SESSION['quizbot']))
{
		$_SESSION['quizbot'] = true;
		$_SESSION['score'] = 0;
		$_SESSION['lastquestion'] = 0;
}else{
}
if(isset($_GET['resetscore']))
{
	$_SESSION['score'] = 0;
	$_SESSION['lastquestion'] = 0;
	die("Progress has been reset, please click <a href=\"index.php\">continue</a>");
}	
if(isset($_POST['insert_answer']))
{
	if(strtolower($_POST['insert_answer']) == strtolower($answers[$_SESSION['lastquestion']]))
	{
		echo "<div align=\"center\">Correct!</div>\n";
		$_SESSION['score']++;
		if($_SESSION['score'] >= count($questions))
		{
			die("Congratulations, you have defeated the mighty QuizB0t, your flag is: brixelCTF{kn0wl3dg3}");
		}
	}else{
		echo "<div align=\"center\">Wrong Answer! The answer is: </div><div id=\"answer\" align=\"center\">" . strtolower($answers[$_SESSION['lastquestion']]) . "</div>\n";
	}
	$_SESSION['lastquestion']++;
	if ($_SESSION['lastquestion'] >= count($questions))
	{
		$_SESSION['lastquestion'] = 0;
		$_SESSION['score'] = 0;
		die("You failed to defeat the mighty QuizB0t, you can try again by refreshing the page.<br>better luck next time.\n");
	}
}
drawHeader();
		echo "<div align=\"center\">\n";
		echo "<h3>Question number " . ($_SESSION['lastquestion'] + 1) . "<h3>\n<h4>" . $questions[$_SESSION['lastquestion']] . " ?</h4>\n";
		echo "<form method=\"POST\" action=\"index.php\"><input type=\"text\" name=\"insert_answer\" id=\"insert_answer\"><input type=\"submit\" name=\"submit\" value=\"answer\"></form>\n";
		echo "</div>\n";
?>
